[helpers]

[default]
depends = []

[default.files]
[default.variables]

[vim.files]
"nvim/plug.vim" = "~/.local/share/nvim/site/autoload/plug.vim"
nvim = "~/.config/nvim"

[vim.variables.vim.plugins.airline]
enabled = true

[vim.variables.vim.plugins.vimtex]
enabled = true

[tmux.files]
tmux = "~/.tmux.conf"

[zsh]
depends = ["profile"]

[zsh.files]
zshrc = "~/.zshrc"
"zshrc.enc" = { target = "~/.zshrc.enc", type = "template", if = "enc" }

[p10k]
depends = ["zsh"]

[p10k.files]
p10k = "~/.p10k.zsh"

[x11.files]
xresources = "~/.Xresources"

[profile.files]
profile = "~/.profile"

[scripts.files]
scripts = "~/scripts"
