includes = []

packages = [
    # cli
    "vim", "tmux", "zsh", "p10k", "profile", "scripts", "vifm", "pbincli",

    # gui
    "x11", "icons", "wallpapers", "i3", "compton", "polybar", "rofi", "fonts", "dunst", "redshift",

    # applications
    "xournalpp",
]

[files]

[variables]
enc = false

# vim
[variables.vim.plugins]
airline = true
vimtex = true
vim-nix = true
vim-svelte = true

# st
[variables.st]
fontsize = 10
alpha = 0.80

# profile
[variables.profile]
auto_start = ""

# i3
[variables.i3]
clipman = true
autotiling = false

# polybar
[variables.polybar.modules]
screenshot = false
rofi = false
updates = true

[variables.polybar.battery]
full-at = 95
